version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: ../docker/php/Dockerfile
    container_name: currencyconv_app
    volumes:
      - ./backend:/var/www/html
    environment:
      - APP_ENV=dev
      - DATABASE_URL=pgsql://symfony:symfony@db:5432/symfony?serverVersion=15&charset=utf8
      - REDIS_URL=redis://redis:6379
      - CURRENCY_API_KEY=fca_live_WuZRkQj0E71a7FkLzrb9IKZLv7tZTJvduBafsol6
    networks:
      - symfony
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    container_name: currencyconv_db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - symfony

  redis:
    image: redis:7-alpine
    container_name: currencyconv_redis
    ports:
      - "6379:6379"
    networks:
      - symfony


volumes:
  db_data:

networks:
  symfony:
    driver: bridge