<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250701173958 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE currency_data (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(3) NOT NULL, symbol VARCHAR(10) NOT NULL, name VARCHAR(100) NOT NULL, symbol_native VARCHAR(20) NOT NULL, decimal_digits SMALLINT NOT NULL, rounding DOUBLE PRECISION NOT NULL, name_plural VARCHAR(100) NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2744B01777153098 ON currency_data (code)');
        $this->addSql('CREATE TABLE currency_pair (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, currency_from INT NOT NULL, currency_to INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_83ED5D1D33ADE204 ON currency_pair (currency_from)');
        $this->addSql('CREATE INDEX IDX_83ED5D1D509A34E2 ON currency_pair (currency_to)');
        $this->addSql('ALTER TABLE currency_pair ADD CONSTRAINT FK_83ED5D1D33ADE204 FOREIGN KEY (currency_from) REFERENCES currency_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE currency_pair ADD CONSTRAINT FK_83ED5D1D509A34E2 FOREIGN KEY (currency_to) REFERENCES currency_data (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE currency_pair DROP CONSTRAINT FK_83ED5D1D33ADE204');
        $this->addSql('ALTER TABLE currency_pair DROP CONSTRAINT FK_83ED5D1D509A34E2');
        $this->addSql('DROP TABLE currency_data');
        $this->addSql('DROP TABLE currency_pair');
    }
}
