<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20250711184407 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE currency_exchange_rate (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, exchange_rate JSON NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pair_id INT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_B9F60EEC7EB8B2A3 ON currency_exchange_rate (pair_id)');
        $this->addSql('ALTER TABLE currency_exchange_rate ADD CONSTRAINT FK_B9F60EEC7EB8B2A3 FOREIGN KEY (pair_id) REFERENCES currency_pair (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE currency_exchange_rate DROP CONSTRAINT FK_B9F60EEC7EB8B2A3');
        $this->addSql('DROP TABLE currency_exchange_rate');
    }
}
